baseurl = "http://fabiorehm.com"
languageCode = "en"
title = "Fabio Rehm's Blog"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/fgrehm\">Fabio Rehm</a> 2017"
disqusShortname = "fgrehm"
googleAnalytics = "UA-37437857-1"
# Number of posts per page
Paginate = 5
enableRobotsTXT = true

# pygmentsUseClassic=true
pygmentsuseclasses = true
# linenos=table

[params.assets]
customCSS = ["css/custom.css"]

[permalinks]
blog = "/blog/:year/:month/:day/:slug/"

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Home" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section

# [params.opengraph.facebook]
# admins = [] # array of Facebook IDs
# appID = ""
# pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "fgrehm"
github = "fgrehm"
email = "fgrehm@gmail.com"
linkedin = "fabiorehm"
facebook = ""
instagram = ""
codepen = ""

[taxonomies]
tag = "tags"

[blackfriday]
hrefTargetBlank = true
plainIdAnchors = true
